config/routes.rb
RtlongCom::Application.routes.draw do

  root to: 'home#show'

  resource :home, controller: :home, only: :show

  get :resume, to: redirect('https://www.dropbox.com/s/x5t88d6cdycp3ty/Resume-Ryan_T_Long.pdf')

  get :github, to: redirect('https://github.com/rtlong')

  get :vcard, to: redirect('/ryan_taylor_long.vcf')

  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get '/auth/failure', to: 'sessions#failure'

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def admin?
    !!current_user
  end

  def current_user
    session[:user]
  end

  helper_method :admin?, :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'splash'

  def show
    #expires_in 3.hours, 'max-stale' => 5.hours, :public => true
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  protect_from_forgery except: :create

  def new
    # This cookie needs to be present for rack-policy to let any of them through
    response.set_cookie 'rack.policy', {
        value: 'true',
        path: '/',
        expires: 1.year.from_now.utc
    }
    redirect_to '/auth/github'
  end

  def create
    if Rails.configuration.allowed_users.any? { |provider, uid| provider.to_s.match(auth_hash.provider) and uid.match(auth_hash.uid) }
      session[:user] = auth_hash.uid
      redirect_to :root, notice: 'Authenticated successfully.'
      AdminMailer.new_login(request).deliver
    else
      redirect_to :root
    end
  end

  def destroy
    reset_session
    redirect_to :root, notice: 'Session destroyed.'
  end

  def failure
    redirect_to :root, alert: params[:message]
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def vertically_center(&block)
    content_for(:content_div_class, 'vertical-center')

    content_tag(:div, class: 'vertical-center', &block)
  end

  def google_analytics
    id = Rails.application.config.google_analytics_id or return
    render 'layouts/google_analytics', id: id
  end

  def title(title = nil)
    if title
      content_for :title, title
    else
      ['RTLong', content_for(:title).presence].compact.join(': ')
    end
  end

  def meta_tags
    @meta ||= {}

    # Set the viewport width to device width for mobile
    @meta['viewport'] ||= 'width=device-width, initial-scale=1.0'
    @meta['format-detection'] ||= 'telephone=no'
    @meta['author'] ||= 'Ryan Taylor Long'
    @meta['copyright'] ||= '&copy; %i Ryan Taylor Long' % [Date.today.year]
    @meta['description'] ||= 'Personal site of Ryan Taylor Long: Ruby developer in San Francisco'
    unless Rails.env.production?
      @meta['robots'] ||= 'noindex, nofollow'
    end

    ActiveSupport::SafeBuffer.new.tap do |output|
      @meta.each do |name, content|
        output << tag(:meta, name: name, content: content)
      end
    end
  end

  def add_meta(name, content)
    @meta ||= {}
    @meta[name.to_s] = content.presence
  end

  def icon(name)
    content_tag(:span, '', class: [name, :icon])
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.haml
.row
  .columns.text-center
    :markdown
      Ruby developer in San Francisco.

.row
  .large-4.columns.text-center
    %p= link_to 'Contact', contact_path
  .large-4.columns.text-center
    %p= link_to 'Github', github_path
  .large-4.columns.text-center
    %p= link_to 'Resume', resume_path

app/views/home/show.html.haml
- add_meta 'description','test'

.row
  .columns.text-center
    :markdown
      Software Engineer in San Francisco.

.row
  .large-4.columns.text-center
    %p
      = link_to github_path do
        GitHub

  .large-4.columns.text-center
    %p= link_to 'Résumé', resume_path

  .large-4.columns.text-center
    %p
      %a(href='#' data-reveal-id='contact-info') Contact

%ul#contact-info.reveal-modal.tiny.vcard
  .hcard-note
    %a.openwebicons-microformats(title="Microformats-enabled: This is an hCard" href="http://microformats.org/about")
      %span hCard

  %li.fn.n
    %span.given-name Ryan
    %span.additional-name Taylor
    %span.family-name Long
  %li
    = link_to 'mailto:ryan@rtlong.com', class: 'email' do
      = icon 'zocial-email'
      ryan@rtlong.com

  -#%li
    %a.tel-link(href="tel:14159006696")
      = icon 'zocial-call'
      %abbr.tel(title='+1.415.900.6696')
        (415) 900-6696
  %li.adr
    = icon 'entypo-location'
    = succeed(',') do
      %span.locality San Francisco
    %abbr.region(title="California") CA
    .hide.country-name United States of America
  %a.hide.photo(href="https://gravatar.com/avatar/053e38be1bd8b18bf8b1c26e11a797ff?s=256") Avatar

  %li
    = link_to vcard_path, title: "Download my vCard" do
      = icon 'entypo-vcard'
      vCard


  %a.close-reveal-modal(href='#') &#215;

app/views/layouts/_admin_toolbar.haml
%nav.top-bar
  %ul.title-area
    / Title Area
    %li.name
      %h1
        %a{:href => "#"} RTLong.com Admin
    / Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        %span Menu
  %section.top-bar-section
    / Left Nav Section
    %ul.left

    / Right Nav Section
    %ul.right
      %li.divider.show-for-small
      %li.has-form
        = link_to 'Logout', logout_path, class: 'button'

app/views/layouts/_google_analytics.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '#{id}', 'rtlong.com');
  ga('send', 'pageview');

app/views/layouts/application.html.haml
!!! 5
/[if lt IE 7] <html class="ie6" lang="en">
/[if IE 7]    <html class="ie7" lang="en">
/[if IE 8]    <html class="ie8" lang="en">
/[if IE 9]    <html class="ie9" lang="en">
/[if (gt IE 9)|!(IE)] <!--> <html lang="en"> <!--

%head
  %meta{charset: 'utf-8'}
  %title= title
  = meta_tags
  = stylesheet_link_tag 'application'
  = javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"
  = javascript_include_tag 'custom.modernizr.js'
  -# = csrf_meta_tag
  -# = google_analytics
%body
  - if admin?
    = render 'layouts/admin_toolbar'

  - flash.each do |level,message|
    .row
      .columns
        .alert-box.radius(class=level data-alert)
          = message
          %a.close(href='#') ×

  .content{class: content_for(:content_div_class)}
    = content_for?(:content) ? yield(:content) : yield

  = yield(:after_content)

  = javascript_include_tag 'application'

</html>

app/views/layouts/splash.html.haml
- content_for :content do
  = vertically_center do

    .row
      .large-4.large-centered.columns
        .row
          .columns.text-center
            %svg.signature{viewBox:"0 0 1000 510", xmlns: "http://www.w3.org/2000/svg", 'xmlns:xlink'=>"http://www.w3.org/1999/xlink"}
              = raw File.read(Rails.root.join('public/images/signature1_plain.svg'))

        = yield

= render template: 'layouts/application'